services:
  traefik:
    image: traefik:v3.1
    restart: unless-stopped
    environment:
      - DOCKER_API_VERSION=1.50
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@ossu.fr"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  cfjjb:
    build: .
    restart: unless-stopped
    expose:
      - "3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cfjjb.rule=Host(`ossu.fr`)"
      - "traefik.http.routers.cfjjb.entrypoints=websecure"
      - "traefik.http.routers.cfjjb.tls.certresolver=letsencrypt"
      - "traefik.http.services.cfjjb.loadbalancer.server.port=3000"
