services:
  cfjjb:
    build: .
    container_name: cfjjb
    restart: unless-stopped
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cfjjb.rule=Host(`ossu.fr`)"
      - "traefik.http.routers.cfjjb.entrypoints=websecure"
      - "traefik.http.routers.cfjjb.tls.certresolver=letsencrypt"
      - "traefik.http.services.cfjjb.loadbalancer.server.port=3000"
